=== Meta-Platform/meta-platform-ecosystem-core-repository/Main.Module/Application.layer/platform-main-application.app/metadata/startup-params-schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "properties": {
    "socket": {
      "type": "string"
    },
    "serverName": {
      "type": "string"
    },
    "ECO_DIRPATH_INSTALL_DATA": {
      "type": "string"
    },
    "REPOS_CONF_FILENAME_REPOS_DATA": {
      "type": "string"
    },
    "REPOS_CONF_EXT_MODULE_DIR": {
      "type": "string"
    },
    "REPOS_CONF_EXT_LAYER_DIR": {
      "type": "string"
    },
    "REPOS_CONF_EXT_GROUP_DIR": {
      "type": "string"
    },
    "REPOS_CONF_EXTLIST_PKG_TYPE": {
      "type": "string"
    },
    "PKG_CONF_DIRNAME_METADATA": {
      "type": "string"
    },
    "EXECUTIONDATA_CONF_DIRNAME_DEPENDENCIES": {
      "type": "string"
    },
    "ECOSYSTEMDATA_CONF_FILENAME_PKG_GRAPH_DATA": {
      "type": "string"
    }
  },
  "required": [
    "socket",
    "serverName",
    "ECO_DIRPATH_INSTALL_DATA",
    "REPOS_CONF_FILENAME_REPOS_DATA",
    "REPOS_CONF_EXT_MODULE_DIR",
    "REPOS_CONF_EXT_LAYER_DIR",
    "REPOS_CONF_EXT_GROUP_DIR",
    "REPOS_CONF_EXTLIST_PKG_TYPE",
    "PKG_CONF_DIRNAME_METADATA",
    "EXECUTIONDATA_CONF_DIRNAME_DEPENDENCIES",
    "ECOSYSTEMDATA_CONF_FILENAME_PKG_GRAPH_DATA"
  ]
}

=== Meta-Platform/meta-platform-ecosystem-core-repository/Main.Module/Application.layer/ecosystem-instance-manager.app/metadata/startup-params.json
{
    "socket":"/home/kadisk/EcosystemData/sockets/ecosystem-instance-manager.app.sock",
    "serverName":"PlatformMainApplicationInstance",
    "ECO_DIRPATH_INSTALL_DATA":"/home/kadisk/EcosystemData",
    "REPOS_CONF_FILENAME_REPOS_DATA":"repositories.json",
    "REPOS_CONF_EXT_MODULE_DIR":"Module",
    "REPOS_CONF_EXT_LAYER_DIR":"layer",
    "REPOS_CONF_EXT_GROUP_DIR":"group",
    "REPOS_CONF_EXTLIST_PKG_TYPE":"app|webapp|webgui|webservice|service|lib",
    "PKG_CONF_DIRNAME_METADATA":"metadata",
    "EXECUTIONDATA_CONF_DIRNAME_DEPENDENCIES": ".dependencies",
    "ECOSYSTEMDATA_CONF_FILENAME_PKG_GRAPH_DATA": "metadata-hierarchy.json"
}
